// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbaUcjiA9SdM9VR253pbTjJZ_TotmsdYg',
    appId: '1:373538048491:web:10ee79ba72ff6ed21571ae',
    messagingSenderId: '373538048491',
    projectId: 'upload-files-393d8',
    authDomain: 'upload-files-393d8.firebaseapp.com',
    storageBucket: 'upload-files-393d8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4UtmADXKipg6_EdQuwmqoICcwGeRirt4',
    appId: '1:373538048491:android:ed0f370fedfbe4ee1571ae',
    messagingSenderId: '373538048491',
    projectId: 'upload-files-393d8',
    storageBucket: 'upload-files-393d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANsLg0QIFmF-nb33ZmMEzkHAh0lbgKox0',
    appId: '1:373538048491:ios:738d2a9f25a8abae1571ae',
    messagingSenderId: '373538048491',
    projectId: 'upload-files-393d8',
    storageBucket: 'upload-files-393d8.appspot.com',
    iosClientId: '373538048491-fdq50oefgnb9gmb52nuusbvj7vh0888q.apps.googleusercontent.com',
    iosBundleId: 'com.appinventiv.healthGroup',
  );
}
